# Generated by Django 4.2.7 on 2025-11-08 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('customer', 'ลูกค้า'), ('seller', 'ผู้ขาย'), ('admin', 'ผู้ดูแลระบบ')], default='customer', max_length=20, verbose_name='บทบาท'),
        ),
    ]
