# Generated by Django 4.2.7 on 2025-11-08 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0003_pet_image_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pet',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='pet',
            name='min_stock_threshold',
            field=models.IntegerField(default=1, verbose_name='จำนวนขั้นต่ำแจ้งเตือน'),
        ),
        migrations.AddField(
            model_name='pet',
            name='stock_quantity',
            field=models.IntegerField(default=1, verbose_name='จำนวนคงเหลือ'),
        ),
    ]
