# Generated by Django 4.2.7 on 2025-11-08 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_method',
            field=models.CharField(choices=[('pickup', 'รับสินค้าเอง'), ('delivery', 'จัดส่งถึงบ้าน')], default='pickup', max_length=20, verbose_name='วิธีการรับสินค้า'),
        ),
        migrations.AddField(
            model_name='order',
            name='pickup_date',
            field=models.DateField(blank=True, null=True, verbose_name='วันที่มารับสินค้า'),
        ),
        migrations.AddField(
            model_name='order',
            name='recipient_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='ชื่อผู้รับสินค้า'),
        ),
    ]
