# Generated by Django 4.2.7 on 2025-11-08 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_delivery_method_order_pickup_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-order_date'], 'verbose_name': 'คำสั่งซื้อ', 'verbose_name_plural': 'คำสั่งซื้อ'},
        ),
    ]
